REM##############################################################################
REM   ____  ____ 
REM  /   /\/   / 
REM /___/  \  /    Vendor: Xilinx 
REM \   \   \/     Version : 2.5
REM  \   \         Application : 7 Series FPGAs Transceivers Wizard
REM  /   /         Filename : simulate_ncsim.bat
REM /___/   /\      
REM \   \  /  \ 
REM  \___\/\___\ 
REM
REM
REM Script SIMULATE_NCSIM.BAT
REM Generated by Xilinx 7 Series FPGAs Transceivers Wizard
REM
REM
REM (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
REM
REM This file contains confidential and proprietary information
REM of Xilinx, Inc. and is protected under U.S. and
REM international copyright and other intellectual property
REM laws.
REM
REM DISCLAIMER
REM This disclaimer is not a license and does not grant any
REM rights to the materials distributed herewith. Except as
REM otherwise provided in a valid license issued to you by
REM Xilinx, and to the maximum extent permitted by applicable
REM law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
REM WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
REM AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
REM BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
REM INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
REM (2) Xilinx shall not be liable (whether in contract or tort,
REM including negligence, or under any other theory of
REM liability) for any loss or damage of any kind or nature
REM related to, arising under or in connection with these
REM materials, including for any direct, or any indirect,
REM special, incidental, or consequential loss or damage
REM (including loss of data, profits, goodwill, or any type of
REM loss or damage suffered as a result of any action brought
REM by a third party) even if such damage or loss was
REM reasonably foreseeable or Xilinx had been advised of the
REM possibility of the same.
REM
REM CRITICAL APPLICATIONS
REM Xilinx products are not designed or intended to be fail-
REM safe, or for use in any application requiring fail-safe
REM performance, such as life-support or safety devices or
REM systems, Class III medical devices, nuclear facilities,
REM applications related to the deployment of airbags, or any
REM other applications that could lead to death, personal
REM injury, or severe property or environmental damage
REM (individually and collectively, "Critical
REM Applications"). Customer assumes the sole risk and
REM liability of any use of Xilinx products in Critical
REM Applications, subject only to applicable laws and
REM regulations governing limitations on product liability.
REM 
REM THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
REM PART OF THIS FILE AT ALL TIMES.

REM***************************** Beginning of Script ***************************
        
REM Ensure the follwoing
REM The library paths for UNISIMS_VER, SIMPRIMS_VER, XILINXCORELIB_VER,
REM UNISIM, SIMPRIM, XILINXCORELIB are set correctly in the cds.lib and hdl.var files.
REM Variables LMC_HOME and XILINX are set 
REM Define the mapping for the work library in cds.lib file. DEFINE work ./work

mkdir work

REM Multi GT Wrapper
ncvlog -work work  ..\..\..\gtwizard_v2_5_gbe_gth.v;
REM GT Wrapper
ncvlog -work work  ..\..\..\gtwizard_v2_5_gbe_gth_gt.v;

ncvlog -work work  ..\..\example_design\gtwizard_v2_5_gbe_gth_init.v;
ncvlog -work work  ..\..\example_design\gtwizard_v2_5_gbe_gth_sync_block.v;
ncvlog -work work  ..\..\example_design\gtwizard_v2_5_gbe_gth_gtrxreset_seq.v;
ncvlog -work work  ..\..\example_design\gtwizard_v2_5_gbe_gth_rxpmarst_seq.v;
ncvlog -work work  ..\..\example_design\gtwizard_v2_5_gbe_gth_rxrate_seq.v;
ncvlog -work work  ..\..\example_design\gtwizard_v2_5_gbe_gth_tx_startup_fsm.v;
ncvlog -work work  ..\..\example_design\gtwizard_v2_5_gbe_gth_rx_startup_fsm.v;
ncvlog -work work  ..\..\example_design\gtwizard_v2_5_gbe_gth_recclk_monitor.v;






REM Clock Module
ncvlog -work work  ..\..\example_design\gtwizard_v2_5_gbe_gth_gt_usrclk_source.v;



REM Example Design modules
ncvlog -work work  ..\..\example_design\gtwizard_v2_5_gbe_gth_gt_frame_gen.v;
ncvlog -work work  ..\..\example_design\gtwizard_v2_5_gbe_gth_gt_frame_check.v;
ncvlog -work work  ..\..\example_design\gtwizard_v2_5_gbe_gth_exdes.v;



ncvlog -work work  ..\gtwizard_v2_5_gbe_gth_tb.v;

REM Other modules
ncvlog -work work $XILINX\verilog\src\glbl.v;

REM Elaborate Design
ncelab -TIMESCALE 1ns/1ps -ACCESS +rw work.gtwizard_v2_5_gbe_gth_TB work.glbl

##Run simulation
ncsim work.gtwizard_v2_5_gbe_gth_TB -input @"simvision -input wave_ncsim.sv"

