################################################################################
##   ____  ____ 
##  /   /\/   / 
## /___/  \  /    Vendor: Xilinx 
## \   \   \/     Version : 2.5
##  \   \         Application : 7 Series FPGAs Transceivers Wizard
##  /   /         Filename : vcs_session.tcl
## /___/   /\     
## \   \  /  \ 
##  \___\/\___\ 
##
##
##
## Script VCS_SESSION.TCL
## Generated by Xilinx 7 Series FPGAs Transceivers Wizard
##
## 
## (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
## 
## This file contains confidential and proprietary information
## of Xilinx, Inc. and is protected under U.S. and
## international copyright and other intellectual property
## laws.
## 
## DISCLAIMER
## This disclaimer is not a license and does not grant any
## rights to the materials distributed herewith. Except as
## otherwise provided in a valid license issued to you by
## Xilinx, and to the maximum extent permitted by applicable
## law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES
## AND CONDITIONS, EXPRESS, IMPLIED, OR STATUTORY, INCLUDING
## BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, NON-
## INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; and
## (2) Xilinx shall not be liable (whether in contract or tort,
## including negligence, or under any other theory of
## liability) for any loss or damage of any kind or nature
## related to, arising under or in connection with these
## materials, including for any direct, or any indirect,
## special, incidental, or consequential loss or damage
## (including loss of data, profits, goodwill, or any type of
## loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was
## reasonably foreseeable or Xilinx had been advised of the
## possibility of the same.
##
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail-
## safe, or for use in any application requiring fail-safe
## performance, such as life-support or safety devices or
## systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any
## other applications that could lead to death, personal
## injury, or severe property or environmental damage
## (individually and collectively, "Critical
## Applications"). Customer assumes the sole risk and
## liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and
## regulations governing limitations on product liability.
## 
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS
## PART OF THIS FILE AT ALL TIMES.

  gui_open_window Wave
  gui_sg_create gtwizard_v2_5_gbe_gth_Group
  gui_list_add_group -id Wave.1 {gtwizard_v2_5_gbe_gth_Group}

  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{FRAME_CHECK_MODULE}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gt0_frame_check.begin_r}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gt0_frame_check.track_data_r}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gt0_frame_check.data_error_detected_r}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gt0_frame_check.start_of_packet_detected_r}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gt0_frame_check.RX_DATA}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gt0_frame_check.ERROR_COUNT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{GT0_gtwizard_v2_5_gbe_gth}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{CPLL Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.CPLLFBCLKLOST_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.CPLLLOCK_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.CPLLLOCKDETCLK_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.CPLLREFCLKLOST_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.CPLLRESET_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Channel - Clocking Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.GTREFCLK0_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Channel - DRP Ports }} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.DRPADDR_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.DRPCLK_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.DRPDI_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.DRPDO_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.DRPEN_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.DRPRDY_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.DRPWE_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Clocking Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.QPLLCLK_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.QPLLREFCLK_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Loopback Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.LOOPBACK_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Power-Down Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXPD_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.TXPD_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{RX Initialization and Reset Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXUSERRDY_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{RX Margin Analysis Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.EYESCANDATAERROR_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Receive Ports - CDR Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXCDRLOCK_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Receive Ports - Clock Correction Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXCLKCORCNT_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Receive Ports - FPGA RX Interface Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXUSRCLK_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXUSRCLK2_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Receive Ports - FPGA RX interface Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXDATA_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Receive Ports - RX 8B/10B Decoder Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXDISPERR_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXNOTINTABLE_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Receive Ports - RX AFE Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.GTHRXN_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Receive Ports - RX Buffer Bypass Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXBUFRESET_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXBUFSTATUS_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Receive Ports - RX Byte and Word Alignment Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXMCOMMAALIGNEN_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXPCOMMAALIGNEN_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Receive Ports - RX Equilizer Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXLPMHFHOLD_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXLPMLFHOLD_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Receive Ports - RX Fabric Output Control Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXOUTCLK_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Receive Ports - RX Initialization and Reset Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.GTRXRESET_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXPCSRESET_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Receive Ports - RX8B/10B Decoder Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXCHARISCOMMA_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXCHARISK_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Receive Ports -RX AFE Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.GTHRXP_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Receive Ports -RX Initialization and Reset Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.RXRESETDONE_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{TX Initialization and Reset Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.GTTXRESET_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.TXUSERRDY_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Transmit Ports - 8b10b Encoder Control Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.TXCHARDISPMODE_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.TXCHARDISPVAL_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Transmit Ports - FPGA TX Interface Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.TXUSRCLK_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.TXUSRCLK2_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Transmit Ports - PCI Express Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.TXELECIDLE_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Transmit Ports - TX Buffer Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.TXBUFSTATUS_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Transmit Ports - TX Data Path interface}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.TXDATA_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Transmit Ports - TX Driver and OOB signaling}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.GTHTXN_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.GTHTXP_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Transmit Ports - TX Fabric Clock Output Control Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.TXOUTCLK_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.TXOUTCLKFABRIC_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.TXOUTCLKPCS_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Transmit Ports - TX Initialization and Reset Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.TXPCSRESET_IN}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.TXRESETDONE_OUT}
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {{Transmit Transmit Ports - 8b10b Encoder Control Ports}} -divider
  gui_sg_addsignal -group gtwizard_v2_5_gbe_gth_Group {gtwizard_v2_5_gbe_gth_TB.gtwizard_v2_5_gbe_gth_exdes_i.gtwizard_v2_5_gbe_gth_init_i.gtwizard_v2_5_gbe_gth_i.gt0_gtwizard_v2_5_gbe_gth_i.TXCHARISK_IN}


  gui_zoom -window Wave.1 -full

