-- Address decode logic for ipbus fabric
-- 
-- This file has been AUTOGENERATED from the address table - do not hand edit
-- 
-- We assume the synthesis tool is clever enough to recognise exclusive conditions
-- in the if statement.
-- 
-- Dave Newbold, February 2011

library IEEE;
use IEEE.STD_LOGIC_1164.all;
use ieee.numeric_std.all;

package ipbus_decode_ipbus_extended_example is

  constant IPBUS_SEL_WIDTH: positive := 5; -- Should be enough for now?
  subtype ipbus_sel_t is std_logic_vector(IPBUS_SEL_WIDTH - 1 downto 0);
  function ipbus_sel_ipbus_extended_example(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t;

-- START automatically  generated VHDL the Thu Jul  5 00:42:22 2018 
  constant N_SLV_CSR: integer := 0;
  constant N_SLV_REG: integer := 1;
  constant N_SLV_PRAM: integer := 2;
  constant N_SLV_PDPRAM: integer := 3;
  constant N_SLV_PDPRAM36: integer := 4;
  constant N_SLV_RAM: integer := 5;
  constant N_SLV_DPRAM: integer := 6;
  constant N_SLV_DPRAM36: integer := 7;
  constant N_SLAVES: integer := 8;
-- END automatically generated VHDL

    
end ipbus_decode_ipbus_extended_example;

package body ipbus_decode_ipbus_extended_example is

  function ipbus_sel_ipbus_extended_example(addr : in std_logic_vector(31 downto 0)) return ipbus_sel_t is
    variable sel: ipbus_sel_t;
  begin

-- START automatically  generated VHDL the Thu Jul  5 00:42:22 2018 
    if    std_match(addr, "------------------00--------000-") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_CSR, IPBUS_SEL_WIDTH)); -- csr / base 0x00000000 / mask 0x0000300e
    elsif std_match(addr, "------------------00--------001-") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_REG, IPBUS_SEL_WIDTH)); -- reg / base 0x00000002 / mask 0x0000300e
    elsif std_match(addr, "------------------00--------010-") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_PRAM, IPBUS_SEL_WIDTH)); -- pram / base 0x00000004 / mask 0x0000300e
    elsif std_match(addr, "------------------00--------011-") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_PDPRAM, IPBUS_SEL_WIDTH)); -- pdpram / base 0x00000006 / mask 0x0000300e
    elsif std_match(addr, "------------------00--------100-") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_PDPRAM36, IPBUS_SEL_WIDTH)); -- pdpram36 / base 0x00000008 / mask 0x0000300e
    elsif std_match(addr, "------------------01------------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_RAM, IPBUS_SEL_WIDTH)); -- ram / base 0x00001000 / mask 0x00003000
    elsif std_match(addr, "------------------10------------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_DPRAM, IPBUS_SEL_WIDTH)); -- dpram / base 0x00002000 / mask 0x00003000
    elsif std_match(addr, "------------------11------------") then
      sel := ipbus_sel_t(to_unsigned(N_SLV_DPRAM36, IPBUS_SEL_WIDTH)); -- dpram36 / base 0x00003000 / mask 0x00003000
-- END automatically generated VHDL

    else
        sel := ipbus_sel_t(to_unsigned(N_SLAVES, IPBUS_SEL_WIDTH));
    end if;

    return sel;

  end function ipbus_sel_ipbus_extended_example;

end ipbus_decode_ipbus_extended_example;

