    
##############################################################################
##   ____  ____
##  /   /\/   /
## /___/  \  /    Vendor: Xilinx
## \   \   \/     Version : 2.5
##  \   \         Application : 7 Series FPGAs Transceivers Wizard
##  /   /         Filename : USER_COMPONENT_NAME+"_xmdf.tcl"
## /___/   /\     
## \   \  /  \
##  \___\/\___\
##
##
## USER_COMPONENT_NAME+"_xmdf.tcl"
## Generated by Xilinx 7 Series FPGAs Transceivers Wizard 
## 
## (c) Copyright 2010-2012 Xilinx, Inc. All rights reserved.
##
## This file contains confidential and proprietary information  of Xilinx, Inc. 
## and is protected under U.S. and international copyright and other 
## intellectual property laws.
##
## DISCLAIMER
## This disclaimer is not a license and does not grant any rights to the 
## materials distributed herewith. Except as otherwise provided in a valid 
## license issued to you by Xilinx, and to the maximum extent permitted by 
## applicable law: (1) THESE MATERIALS ARE MADE AVAILABLE "AS IS" AND
## WITH ALL FAULTS, AND XILINX HEREBY DISCLAIMS ALL WARRANTIES AND CONDITIONS, 
## EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO WARRANTIES OF 
## MERCHANTABILITY, NON-INFRINGEMENT, OR FITNESS FOR ANY PARTICULAR PURPOSE; 
## and (2) Xilinx shall not be liable (whether in contract or tort, including 
## negligence, or under any other theory of liability) for any loss or damage 
## of any kind or nature related to, arising under or in connection with these
## materials, including for any direct, or any indirect, special, incidental, 
## or consequential loss or damage (including loss of data, profits, goodwill, 
## or any type of loss or damage suffered as a result of any action brought
## by a third party) even if such damage or loss was reasonably foreseeable 
## or Xilinx had been advised of the possibility of the same.
##
## CRITICAL APPLICATIONS
## Xilinx products are not designed or intended to be fail- safe, or for use 
## in any application requiring fail-safe performance, such as life-support 
## or safety devices or systems, Class III medical devices, nuclear facilities,
## applications related to the deployment of airbags, or any other applications 
## that could lead to death, personal injury, or severe property or environmental 
## damage (individually and collectively, "Critical Applications"). Customer 
## assumes the sole risk and liability of any use of Xilinx products in Critical
## Applications, subject only to applicable laws and regulations governing 
## limitations on product liability.
##
## THIS COPYRIGHT NOTICE AND DISCLAIMER MUST BE RETAINED AS PART OF THIS FILE 
## AT ALL TIMES
##
##############################################################################
# ::gen_comp_name_xmdf::xmdfApplyParams
# The package naming convention is <core_name>_xmdf
package provide gtwizard_v2_5_gbe_gth_xmdf 1.0

# This includes some utilities that support common XMDF operations
package require utilities_xmdf

# Define a namespace for this package. The name of the name space
# is <core_name>_xmdf
namespace eval ::gtwizard_v2_5_gbe_gth_xmdf {
# Use this to define any statics
}

# Function called by client to rebuild the params and port arrays
# Optional when the use context does not require the param or ports
# arrays to be available.
proc ::gtwizard_v2_5_gbe_gth_xmdf::xmdfInit { instance } {
# Variable containg name of library into which module is compiled
# Recommendation: <module_name>
# Required
utilities_xmdf::xmdfSetData $instance Module Attributes Name gtwizard_v2_5_gbe_gth
}
# ::gtwizard_v2_5_gbe_gth_xmdf::xmdfInit

# Function called by client to fill in all the xmdf* data variables
# based on the current settings of the parameters
proc ::gtwizard_v2_5_gbe_gth_xmdf::xmdfApplyParams { instance } {

set fcount 0
# Array containing libraries that are assumed to exist
# Examples include unisim and xilinxcorelib
# Optional
# In this example, we assume that the unisim library will
# be magically
# available to the simulation and synthesis tool

utilities_xmdf::xmdfSetData $instance FileSet $fcount type logical_library
utilities_xmdf::xmdfSetData $instance FileSet $fcount logical_library unisim
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/doc/ug769_gtwizard.pdf
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/gtwizard_v2_5_gbe_gth_exdes.xcf
utilities_xmdf::xmdfSetData $instance FileSet $fcount type ucf
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/gtwizard_v2_5_gbe_gth_exdes.ucf
utilities_xmdf::xmdfSetData $instance FileSet $fcount type ucf
incr fcount


utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/gtwizard_v2_5_gbe_gth_gt_usrclk_source.v
utilities_xmdf::xmdfSetData $instance FileSet $fcount type verilog 
incr fcount



utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/gtwizard_v2_5_gbe_gth_gtrxreset_seq.v
utilities_xmdf::xmdfSetData $instance FileSet $fcount type verilog 
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/gtwizard_v2_5_gbe_gth_rxpmarst_seq.v
utilities_xmdf::xmdfSetData $instance FileSet $fcount type verilog 
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/gtwizard_v2_5_gbe_gth_rxrate_seq.v
utilities_xmdf::xmdfSetData $instance FileSet $fcount type verilog 
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/gtwizard_v2_5_gbe_gth_init.v
utilities_xmdf::xmdfSetData $instance FileSet $fcount type verilog 
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/gtwizard_v2_5_gbe_gth_sync_block.v
utilities_xmdf::xmdfSetData $instance FileSet $fcount type verilog 
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/gtwizard_v2_5_gbe_gth_tx_startup_fsm.v
utilities_xmdf::xmdfSetData $instance FileSet $fcount type verilog 
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/gtwizard_v2_5_gbe_gth_rx_startup_fsm.v
utilities_xmdf::xmdfSetData $instance FileSet $fcount type verilog 
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/gtwizard_v2_5_gbe_gth_recclk_monitor.v
utilities_xmdf::xmdfSetData $instance FileSet $fcount type verilog 
incr fcount








utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/gtwizard_v2_5_gbe_gth_gt_frame_gen.v
utilities_xmdf::xmdfSetData $instance FileSet $fcount type verilog 
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/gtwizard_v2_5_gbe_gth_gt_frame_check.v
utilities_xmdf::xmdfSetData $instance FileSet $fcount type verilog 
incr fcount


   

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth_gt.v
utilities_xmdf::xmdfSetData $instance FileSet $fcount type verilog 
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth.v
utilities_xmdf::xmdfSetData $instance FileSet $fcount type verilog 
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/gtwizard_v2_5_gbe_gth_exdes.v
utilities_xmdf::xmdfSetData $instance FileSet $fcount type verilog 
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth.veo
utilities_xmdf::xmdfSetData $instance FileSet $fcount type verilog_template
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/simulation/gtwizard_v2_5_gbe_gth_tb.v
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount


utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/implement/chipscope_project.cpj
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/data_vio.ngc
utilities_xmdf::xmdfSetData $instance FileSet $fcount type ngc
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/ila.ngc
utilities_xmdf::xmdfSetData $instance FileSet $fcount type ngc
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/icon.ngc
utilities_xmdf::xmdfSetData $instance FileSet $fcount type ngc
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/chipscope_vio.ngc
utilities_xmdf::xmdfSetData $instance FileSet $fcount type ngc
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/chipscope_ila.ngc
utilities_xmdf::xmdfSetData $instance FileSet $fcount type ngc
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/example_design/chipscope_icon.ngc
utilities_xmdf::xmdfSetData $instance FileSet $fcount type ngc
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/implement/implement.bat
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/implement/implement.sh
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/implement/implement_synplify.bat
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/implement/implement_synplify.sh
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/implement/synplify.prj
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/implement/xst.prj
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/implement/xst.scr
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/implement/planAhead_ise.sh
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/implement/planAhead_ise.bat
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/implement/planAhead_ise.tcl
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/simulation/functional/gt_rom_init_rx.dat
utilities_xmdf::xmdfSetData $instance FileSet $fcount type txt
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/simulation/functional/gt_rom_init_tx.dat
utilities_xmdf::xmdfSetData $instance FileSet $fcount type txt
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/gtwizard_v1_5_readme.txt
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/gtwizard_v2_5_gbe_gth.pf
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/simulation/functional/simulate_isim.bat
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/simulation/functional/simulate_isim.sh
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/simulation/functional/simulate_mti.do
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/simulation/functional/simulate_ncsim.bat
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/simulation/functional/simulate_ncsim.sh
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/simulation/functional/simulate_vcs.sh
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/simulation/functional/ucli_commands.key
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/simulation/functional/vcs_session.tcl
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/simulation/functional/wave_isim.tcl
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/simulation/functional/wave_mti.do
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth/simulation/functional/wave_ncsim.sv
utilities_xmdf::xmdfSetData $instance FileSet $fcount type Ignore
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth.xco
utilities_xmdf::xmdfSetData $instance FileSet $fcount type coregen_ip
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount relative_path gtwizard_v2_5_gbe_gth_xmdf.tcl
utilities_xmdf::xmdfSetData $instance FileSet $fcount type AnyView
incr fcount

utilities_xmdf::xmdfSetData $instance FileSet $fcount associated_module gtwizard_v2_5_gbe_gth
incr fcount

}

# ::gen_comp_name_xmdf::xmdfApplyParams



